### ISSUE TITLE
Possible unused Font

### ISSUE THREAD

**Issue by at-the-vr** [srleom/astro-theme-resume#1]
I found [Clash Display](https://github.com/srleom/astro-theme-resume/blob/main/public/fonts/ClashDisplay-Variable.ttf) but its not configured in [app.css](https://github.com/srleom/astro-theme-resume/blob/main/src/styles/app.css) and is nowhere used in the Site 😕

**Comment by srleom** [comment]
Thanks for pointing it out! I initially wanted to use Clash Display as a display font but I decided against it in the end. I've now removed the unused Clash Display font in a new update to the repo. Hope this helps :)
